library(dplyr)
library(ggplot2)

#' @param gene.dat gene data operate by tTest
#' @return gene.bin contains coverage
calculateCoverage <- function(gene.dat) {
  gene.dat <- gene.dat %>%
    mutate(bin = case_when(
      log2(FC) < log2(1.1) & log2(FC) > -log2(1.1)  ~ "<10%",
      (log2(FC) < log2(1.2) & log2(FC) >= log2(1.1)) | (log2(FC) <= -log2(1.1) & log2(FC) > -log2(1.2)) ~ "<20%", 
      (log2(FC) < log2(1.3) & log2(FC) >= log2(1.2)) | (log2(FC) <= -log2(1.2) & log2(FC) > -log2(1.3)) ~ "<30%", 
      (log2(FC) < log2(1.4) & log2(FC) >= log2(1.3)) | (log2(FC) <= -log2(1.3) & log2(FC) > -log2(1.4)) ~ "<40%", 
      (log2(FC) < log2(1.5) & log2(FC) >= log2(1.4)) | (log2(FC) <= -log2(1.4) & log2(FC) > -log2(1.5)) ~ "<50%", 
      (log2(FC) < log2(1.6) & log2(FC) >= log2(1.5)) | (log2(FC) <= -log2(1.5) & log2(FC) > -log2(1.6)) ~ "<60%", 
      (log2(FC) < log2(1.7) & log2(FC) >= log2(1.6)) | (log2(FC) <= -log2(1.6) & log2(FC) > -log2(1.7)) ~ "<70%", 
      (log2(FC) < log2(1.8) & log2(FC) >= log2(1.7)) | (log2(FC) <= -log2(1.7) & log2(FC) > -log2(1.8)) ~ "<80%", 
      (log2(FC) < log2(1.9) & log2(FC) >= log2(1.8)) | (log2(FC) <= -log2(1.8) & log2(FC) > -log2(1.9)) ~ "<90%", 
      (log2(FC) < log2(2) & log2(FC) >= log2(1.9)) | (log2(FC) <= -log2(1.9) & log2(FC) > -log2(2)) ~ "<100%", 
      abs(log2(FC)) >= 1~ ">=100%")
    )
  
  gene.bin <- as.data.frame(table(gene.dat$bin))
  colnames(gene.bin) <- c("bin", "count")
  
  level <- c("<10%", "<20%", "<30%", "<40%", "<50%", "<60%", "<70%", 
             "<80%", "<90%", "<100%", ">=100%")
  gene.bin$bin <- factor(gene.bin$bin, levels = level)
  gene.bin <- gene.bin[order(gene.bin$bin), ]
  
  insertLine <- function(value, x, after) {
    if (after < nrow(x)) {
      return(rbind(x[1: after, ], value, x[after+1: nrow(x), ]))
    } else {
      return(rbind(x, value))
    }
  }
  
  if (nrow(gene.bin) == 11) {
    for (i in 1: 11) {
      gene.bin$cumulative[i] <- sum(gene.bin$count[1: i]/sum(gene.bin$count))
    }
  } else {
    for (i in 1: nrow(gene.bin)) {
      gene.bin$cumulative[i] <- sum(gene.bin$count[1: i]/sum(gene.bin$count))
    }
    bin.diff <- setdiff(level, gene.bin$bin)
    pos <- which(level %in% bin.diff)
    for (i in 1: length(pos)) {
      bin.sup.tmp <- gene.bin[pos[i] - 1, ]  # get previous line
      bin.sup.tmp[1: 2] <- c(bin.diff[i], 0)
      gene.bin <- insertLine(bin.sup.tmp, gene.bin, after = pos[i] - 1) 
    }
  }
  gene.bin <- na.omit(gene.bin)
  row.names(gene.bin) <- 1: length(level)
  gene.bin$count <- as.numeric(gene.bin$count)
  gene.bin$bin <- factor(gene.bin$bin, levels = level)
  gene.bin <- gene.bin[order(gene.bin$bin), ]
  return(gene.bin)
}


#' @description
#' inferring fold change threshold by cumulative threshold
#' @param gene.bin generated by calcualteCoverage
#' @param coverage.threshold coverage threshold, default 0.88, p.s. >= 0.88
#' @return fold change threshold
thresholdInference <- function(gene.bin, coverage.threshold) {
  gene.bin$threshold <- c(seq(1.1, 2, 0.1), 2)
  for (i in 1: 11) {
    if (gene.bin$cumulative[i] >= 0.88) {
      threshold <- gene.bin$threshold[i]
      break
    }
  }
  if (threshold) return(threshold) else return(2)
}


#' @param gene.bin generated by calcualteCoverage
#' @return coverage plot, ggplot2 object
coveragePlot <- function(gene.bin) {
  binplot <- ggplot() + 
    geom_bar(data = gene.bin, 
             aes(x=bin, weight=count), 
             fill="#698e31") + 
    geom_line(data = gene.bin, 
              aes(x=bin, y=cumulative * sum(gene.bin$count), group=F), 
              linewidth = 1.5, 
              color = "#E7B800") + 
    geom_hline(yintercept = 0.88*sum(gene.bin$count), 
               linetype = 4, 
               linewidth = 1) + 
    scale_y_continuous(name="Count", 
                       sec.axis = sec_axis(trans=~.*100/sum(gene.bin$count), name="Coverage (%)")) + 
    xlab(label = element_blank()) + 
    theme(axis.text = element_text(size = 10), 
          axis.text.x = element_text(angle = 45, hjust = 1))
  return(binplot)
}
